platform:ios, '8.0'

use_frameworks!

pod 'SDWebImage'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'Alamofire'
pod 'GRMustache'
pod 'BaiduMapKit' 

link_with 'MenTouGou', 'MenTouGouTests', 'MenTouGouUITests'